---
- name: Create EC2 instance et installer Docker
  hosts: localhost
  connection: local
  gather_facts: true
  vars: 
    ansible_ssh_private_key_file: ~/first.pem
    ansible_user: ec2-user
  tasks: 
  - name: launching ec2
    amazon.aws.ec2_instance:
       name: "myEC5instance" 
       instance_type: t2.micro
       key_name: first
       image_id: ami-0111c5910da90c2a7
       region: eu-west-3
       security_group: my_security_group
       count: 1
       vpc_subnet_id: subnet-07feccaf262b84173
       wait: yes
       volumes: 
          - device_name: /dev/sdb
            ebs: 
              volume_size: 8
              delete_on_termination: true
       tags: 
          Name: myec2instance
       network: 
          public_ip: yes
       instance_initiated_shutdown_behavior: stop
       termination_protection: no
    register: ec2
  - name: Ajouter L'instances à l'inventaire
    ansible.builtin.add_host:
      hostname: "{{ item.network_interfaces[0].association.public_ip }}"
      groupname: ec2hosts
    loop: "{{ ec2.instances }}"
    
  - name: Attendre que SSH soit prêt 
    ansible.builtin.wait_for:
      host: "{{ item.network_interfaces[0].association.public_ip }}"
      port: 22 
      delay: 100
      timeout: 320
      state: started
    loop: "{{ ec2.instances }}"

- name: Installer Docker sur l'instance EC2
  hosts: ec2hosts
  become: yes
  tasks: 
        - name: Mettre à jour le cache yum 
          yum:
              name: '*'
              state: latest
            
        - name: Insatller Docker
          yum:
             name: docker
             state: present
           
        - name: Démarrer le service Docker
          service:
               name: docker
               state: started 
               enabled: yes
    
 
