---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: true 
 
  tasks: 
  - name: launching ec2
    amazon.aws.ec2_instance:
       name: "myEC5instance" 
       instance_type: t2.micro
       key_name: first
       image_id: ami-0111c5910da90c2a7
       region: eu-west-3
       security_group: my_security_group
       count: 1
       vpc_subnet_id: subnet-07feccaf262b84173
       wait: yes
       volumes: 
          - device_name: /dev/sdb
            ebs: 
              volume_size: 8
              delete_on_termination: true
       tags: 
          Name: myec2instance
       network: 
          assign_public_ip: yes
       instance_initiated_shutdown_behavior: stop
       termination_protection: no
