- name: Création de pods avec Ansible
  hosts: ec2hosts
  gather_facts: no
  
  tasks:
    - name: Création des fichiers YAML pour les pods
      template:
        src: pod_template.yaml
        dest: "pod{{ item }}.yaml"
      loop: "{{ range(1, pod_count | int + 1) | list }}"
      vars:
        vars:
          pod_count: "{{ pod_count_var }}"  # Utiliser une variable pour le nombre de pods


    - name: Appliquer les fichiers YAML pour créer les pods
      command: "microk8s kubectl apply -f pod{{ item }}.yaml"
      loop: "{{ range(1, pod_count | int + 1) | list }}"
      register: result
      changed_when: result.rc == 0

    - name: Afficher les pods créés
      command: "microk8s kubectl get pods"
